name: Infrastructure as code

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Save Terraform output
        run: terraform output -json > tf-output.json

      - name: Debug - Check if tf-output.json exists
        run: |
          ls -al
          cat tf-output.json

      - name: Move output to root for upload
        run: mv tf-output.json ../tf-output.json
        working-directory: infra

      - name: Upload terraform Output as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-output
          path: tf-output.json

  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Wait for MySQL to be Ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..60}; do
            if mysqladmin ping -h127.0.0.1 -uroot -p"${{ secrets.MYSQL_PASSWORD }}" --silent; then
              echo "✅ MySQL is up and running!"
              break
            fi
            echo "⏳ Waiting for MySQL... ($i/60)"
            sleep 2
          done

      - name: Build with maven
        run: mvn clean install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: logger-jar
          path: target/*.jar

      - name: Download Terraform Output
        uses: actions/download-artifact@v4
        with:
          name: terraform-output

      - name: Rename tf-output.json if needed
        run: |
          if [ -f tf-output.json ]; then
            echo "✅ File is already in current dir"
          elif [ -f terraform-output.json ]; then
            mv terraform-output.json tf-output.json
          else
            echo "❌ tf-output.json not found!"
            exit 1
          fi

      - name: Show contents of tf-output.json
        run: cat tf-output.json

      - name: Extract EC2 Public IP
        id: extract-ip
        run: |
          echo "Parsing tf-output.json for public_ip"
          jq '.' tf-output.json  # Debug the entire structure
          IP=$(jq -r '.public_ip.value' tf-output.json)  # Extract the public IP
          echo "EC2_IP=$IP" >> $GITHUB_ENV

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "target/*.jar"
          target: "~/logger-app/"

      - name: Run App on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            pkill -f 'java' || true
            nohup java -jar ~/logger-app/*.jar > logger.log 2>&1 &
